name: tsforecast
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
# brew install --cask cmake
dependencies:
  - python=3.11
  - pip:
      - rpy2==3.5.17
      - ipython=7.34.0
      - ipykernel==6.5.0
